// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/DeepakDP5/zee6do-server/internal/database"
	"github.com/DeepakDP5/zee6do-server/internal/server"
	"github.com/DeepakDP5/zee6do-server/pkg/config"
)

// InitializeApp wires all dependencies and returns the fully assembled App.
func InitializeApp(ctx context.Context, cfg *config.Config) (*App, error) {
	logger := provideLogger(cfg)
	mongoClient, err := database.NewMongoClient(ctx, cfg, logger)
	if err != nil {
		return nil, err
	}
	healthChecker := server.NewHealthChecker()
	app := newApp(cfg, logger, mongoClient, healthChecker)
	return app, nil
}
